name: cd
on:
  pull_request:
    branches: [master]
    types: [closed]
  workflow_dispatch:

jobs:
  build_push_docker_image:
    name: Build and push metatlas_shifter docker image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v2
    - name: generate time based tag
      id: timestamp
      run: |
        DATE_TIME=$(date -u +"%Y%m%d_%H%M%S")
        echo "::set-output name=date_time::${DATE_TIME}"
    - name: Login to GHCR
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build Docker images
      id: build
      uses: docker/build-push-action@v2.7.0
      with:
        context: ./docker
        platforms: linux/amd64
        cache-from: type=registry,ref=ghcr.io/biorack/bastet:latest
        cache-to: type=inline
        tags: |
          ghcr.io/biorack/bastet:${{ steps.timestamp.outputs.date_time }}
          ghcr.io/biorack/bastet:latest
        push: true
